# =============================== #
# NoWather
# auther the_karura
# github: https://github.com/thekarura/NoWather
# =============================== #
worlds:
- example_1
- example_2
- example_3
- example_4
- example_5